// flashcards.js
  const flashcards = [
    // { side1: 'Claro', side2: 'Clear?' },
    // { side1: 'Hay preguntas?', side2: 'Any questions?' },
    // { side1: 'Qué tal?', side2: 'How are you - informal' },
    // { side1: 'Buenas tardes', side2: 'Good evening (after 12, but normally after 14-20 sunset)' },
    // { side1: 'Buenas noches', side2: 'Good night' },
    // { side1: 'Buenos dias', side2: 'Good morning' },
    // { side1: 'Hasta pronto', side2: 'See you soon' },
    // { side1: 'Chau', side2: 'Bye' },
    // { side1: 'Hasta luego', side2: 'See you later' },
    // { side1: 'Adios', side2: 'Bye - formal' },
    // { side1: 'Me llamo', side2: 'My name' },
    // { side1: 'Me apellido', side2: 'My surname' },
    // { side1: 'Qué significa?', side2: 'What does it mean?' },
    // { side1: 'Puedes repetir', side2: 'Can you repeat?' }, 
    // { side1: 'Qué significa?', side2: 'What does it mean?' },
    // { side1: 'Cómo se dice en español?', side2: 'How do you say in Spanish?' },
    // { side1: 'Más despacio', side2: 'More slowly' },    
    // { side1: 'No entiendo / no comprendo', side2: 'I don\'t understand' },
    // { side1: 'En que trabajas', side2: 'What is your profession?' },
    // { side1: 'Donde trabajas', side2: 'Where do you work?' },
    { side1: 'No recuerdo', side2: 'I don\'t remember' },
    { side1: 'No sé', side2: 'I don\'t know' },    

    { side1: 'Los dos', side2: 'Both' },
    { side1: 'Algunas', side2: 'Some' },
    { side1: 'Cosa', side2: 'Thing' },
    { side1: 'Ir de compras / hacer la compra', side2: 'Go shopping / do the grocery' },
    { side1: 'Clima suave', side2: 'Mild climate' },
    { side1: 'Es humedo', side2: 'It\'s wet' },
    { side1: 'Hacer senderismo', side2: 'Go hiking' },
    { side1: 'Cada vez', side2: 'Each time' },
    { side1: 'Una vez', side2: 'One time' },
    { side1: 'Dos veces', side2: 'Two times' },
    { side1: 'Tres veces', side2: '3 times' },
    { side1: 'Vecino', side2: 'Neighbor' },
    { side1: 'Pronto', side2: 'Soon' },
    { side1: 'Todavia no', side2: 'Not yet' },
    { side1: 'Poblada', side2: 'Populated' },
    { side1: 'Peregrinaje', side2: 'Pilgrimage' },
    { side1: 'Reconocimiento', side2: 'Well known <br/> syn: conocido' },
    { side1: 'Cerca de', side2: 'Next to, nearby' },
    { side1: 'Casi', side2: 'Almost' },
    { side1: 'Mas seguras', side2: 'More secure' },
    { side1: 'Ubicacion', side2: 'Location' },
    { side1: 'Ademas', side2: 'In addition, moreover <br /> syn. tambien' },
    { side1: 'Alrededores', side2: 'Surroundings' },
    { side1: 'Conosido', side2: 'Well known, famous<br/> syn: Reconocimiento' },
    { side1: 'Valle', side2: 'Valley' },
    { side1: 'Despues', side2: 'After' },
    { side1: 'Norte/Este/Sur/Oeste', side2: 'North/East/South/West' },
    { side1: 'El sureste', side2: 'Southeast' },
    { side1: 'Edificios', side2: 'Buildings' },
    { side1: 'Restos', side2: 'Ruins' },
    { side1: 'Poblacion', side2: 'Population' },
    { side1: 'Siglos', side2: 'Centuries' },
    { side1: 'El casco antiguo', side2: 'Old town' },
    { side1: 'Quiza', side2: 'Maybe' },
    { side1: 'Prefiero los equipos italianos', side2: 'I prefer Italian teams' },
    { side1: 'Me gustaria viajar', side2: 'I would like to travel' },
    { side1: 'Al menos', side2: 'At least' },
    { side1: 'Gente', side2: 'People' },
    { side1: 'Amable', side2: 'Kind' },
    { side1: 'Arena', side2: 'Sand' },
    { side1: 'Calor', side2: 'Heat' },
    { side1: 'Humedo', side2: 'Humid' },
    { side1: 'Llueve', side2: 'It rains' },
    { side1: 'Tener ganas', side2: 'To feel like doing something' },
    { side1: 'Tengo ganas de ir de vacaciones', side2: 'I really want to go on vacation<br />Tener ganas - really want doing something'},
    { side1: 'Alli', side2: 'There' },
    { side1: 'Divertida', side2: 'Fun' },
    { side1: 'Bebida', side2: 'Drink' },
    { side1: 'Cordillera', side2: 'Mountain range' },
    { side1: 'Hace sol', side2: 'It\'s sunny' },
    { side1: 'Hace calor', side2: 'It\'s hot' },
    { side1: 'Hace frio', side2: 'It\'s cold' },
    { side1: 'Hace viento', side2: 'It\'s windy' },
    { side1: 'Esta nublado', side2: 'It\'s cloudy' },
    { side1: 'Es seco', side2: 'It\'s dry' },
    { side1: 'La primavera', side2: 'Spring' },
    { side1: 'El verano', side2: 'Summer' },
    { side1: 'El otoño', side2: 'Autumn' },
    { side1: 'El invierno', side2: 'Winter' },
    { side1: '100 cien; <br /> 101 - 199 ciento uno - ciento noventa y nueve<br /> 200 - doscientos/as<br /> 300 - trescientos/as<br />    400 - cuatrocientos/as<br /> 500 - quinentos/as<br /> 600 - seiscientos/as<br />700 - setecientos/as<br />800 - ochocientos/as<br />900 - novecientos/as', side2: 'numbers )))' },

    { side1: '<b>IR + <u>A + INFINITIVO</u></b><br /> mañana voy a comer pasta<br />vas a viajar a España<br /> va a estudiar español', side2: 'Simple Future<br />Go with A + Infinitive' },

    { side1: 'Camiseta de manga corta/de manga larga<br />de rayas<br />de cuadros<br />de tirantes<br />estampado/a/os/as', side2: 'T-shirt/Long Sleeves<br />with stripesd<br />with squares<br />with straps<br />with print' },

    { side1: '<b>Adjectivos para describir</b><br />Bonita/o/as/os<br />fea/o/as/os<br />clásica/o/as/os<br />práctica/o/as/os<br />moderna/o/as/os', side2: 'Pretty<br />Ugly<br />Classical<br />Practical<br />Modern' },

    { side1: '<b>Precio</b><br />Cara/o/as/os<br />Barata/o/as/os', side2: 'Expensive<br />Chip' },

    { side1: '<b>Adjectivos para describir</b><br />Bonita/o/as/os<br />fea/o/as/os<br />clásica/o/as/os<br />práctica/o/as/os<br />moderna/o/as/os', side2: 'Pretty<br />Ugly<br />Classical<br />Practical<br />Modern' },

    { side1: 'Blanca/o/as/os<br />Amarilla/o/as/os<br />Roja/o/as/os<br />Negra/o/as/os', side2: 'White<br />Yellow<br />Red<br />Black' },
    { side1: 'Naranja/as<br />Rosa/as<br />Lila/as<br />Verde/es<br />Azul/es<br />Gris/es<br />Marrón/es<br /><b>beis</b>', side2: 'Orange<br />Rose<br />Lilly<br />Green<br />Blue<br />Grey<br />Brown<br />Beige' },

    { side1: '<b>Viajar</b><br />Viajo<br />Viajas<br />Viaja<br />Viajamos<br />Viajáis<br />Viajan', side2: 'To Travel' },
    { side1: '<b>Ver</b><br />Veo<br />Ves<br />Ve<br />Vemos<br />Veis<br />Ven', side2: 'To See' },
    { side1: '<b>Tocar</b><br />Toco<br />Tocas<br />Toca<br />Tocamos<br />Tocáis<br />Tocan', side2: 'To Play (instrument)' },
    { side1: '<b>Actuar</b><br />Actúo<br />Actúas<br />Actúa<br />Actuamos<br />Actuáis<br />Actúan', side2: 'To Act (Play in movies, cinema, etc)' },
    { side1: '<b>Hacer</b><br />Hago<br />Haces<br />Hace<br />Hacemos<br />Hacéis<br />Hacen', side2: 'To Do' },
    { side1: '<b>Jugar</b><br />Juego<br />Juegas<br />Juega<br />Jugamos<br />Jugáis<br />Juegan', side2: 'To Play game' },
    { side1: '<b>Escuchar</b><br />Escucho<br />Escuchas<br />Escucha<br />Escuchamos<br />Escucháis<br />Escuchan', side2: 'To Listen' },
    { side1: '<b>Buscar</b><br />Busco<br />Buscas<br />Busca<br />Buscamos<br />Buscáis<br />Buscan', side2: 'To Search' },
    { side1: '<b>Leer</b><br />Leo<br />Lees<br />Lee<br />Leemos<br />Leéis<br />Leen', side2: 'To Read' },
    { side1: '<b>Mejorar</b><br />Mejoro<br />Mejoras<br />Mejora<br />Mejoramos<br />Mejoráis<br />Mejoran', side2: 'To Improve' },
    { side1: '<b>Pasar</b><br />Paso<br />Pasas<br />Pasa<br />Pasamos<br />Pasáis<br />Pasan', side2: 'To Spend time' },
    { side1: '<b>Creer</b><br />Creo<br />Crees<br />Cree<br />Creemos<br />Creéis<br />Creen', side2: 'To Believe, To Think' },
    { side1: '<b>Elegir</b><br />Elijo<br />Eliges<br />Elige<br />Elegimos<br />Elegís<br />Eligen', side2: 'To Choose' },
    
    { side1: '<b>Ser</b><br />Soy<br />Eres<br />Es<br />Somos<br />Sois<br />Son', side2: 'To Be <br /> CARACTERISTICA or EVENT<br />Soy espanol<br />El concierto es en la opera' },
    { side1: '<b>Estar</b><br />Estoy<br />Estás<br />Está<br />Estamos<br />Estáis<br />Están', side2: 'To Be <br /> Temporary or Located <br />Estoy enfermo<br />Riga esta en Letonia' },
    { side1: '<b>Llegar</b><br />Llego<br />Llegas<br />Llega<br />Llegamos<br />Llegáis<br />Llegan', side2: 'To Arrive' },

    { side1: '<b>Tener</b><br />Tengo<br />Tienes<br />Tiene<br />Tenemos<br />Tenéis<br />Tienen', side2: 'To have' },
    { side1: '<b>Decir</b><br />Digo<br />Dices<br />Dice<br />Decimos<br />Decís<br />Dicen', side2: 'To say' },
    { side1: '<b>Ir</b><br />Voy<br />Vas<br />Va<br />Vamos<br />Vais<br />Van', side2: 'To go' },
    { side1: '<b>Poder</b><br />Puedo<br />Puedes<br />Puede<br />Podemos<br />Podéis<br />Pueden', side2: 'To be able to' },
    { side1: '<b>Querer</b><br />Quiero<br />Quieres<br />Quiere<br />Queremos<br />Queréis<br />Quieren', side2: 'To want' },
    { side1: '<b>Saber</b><br />Sé<br />Sabes<br />Sabe<br />Sabemos<br />Sabéis<br />Saben', side2: 'To know' },
    { side1: '<b>Visitar</b><br />Visito<br />Visitas<br />Visita<br />Visitamos<br />Visitáis<br />Visitan', side2: 'To visit' },
    { side1: '<b>Salir</b><br />Salgo<br />Sales<br />Sale<br />Salimos<br />Salís<br />Salen', side2: 'To Leave,<br /> To Go out <br />, To Hangout' },
    { side1: '<b>Cenar</b><br />Ceno<br />Cenas<br />Cena<br />Cenamos<br />Cenáis<br />Cenan', side2: 'To Dine' },
    { side1: '<b>Comprar</b><br />Compro<br />Compras<br />Compra<br />Compramos<br />Comprais<br />Compran', side2: 'To Buy' },
    { side1: '<b>Vender</b><br />Vendo<br />Vendes<br />Vende<br />Vendemos<br />Vendeis<br />Venden', side2: 'To Sell' },
    { side1: '<b>Llevar</b><br />Llevo<br />Llevas<br />Lleva<br />Llevamos<br />Llevais<br />Llevan', side2: 'To Wear<br /> To Take' },
    { side1: '<b>Pensar</b><br />Pienso<br />Piensas<br />Piensa<br />Pensamos<br />Pensais<br />Piensan', side2: 'To Think' },
  ];
  export default flashcards;