// flashcards.js
  const flashcards = [
    { question: 'Qué significa?', answer: 'What does it mean?' },
    { question: 'Cómo se dice en español?', answer: 'How do you say in Spanish?' },
    { question: 'Puedes repetir?', answer: 'Can you repeat?' },
    { question: 'Más despacio', answer: 'More slowly' },
    { question: 'Claro', answer: 'Clear?' },
    { question: 'Hay preguntas?', answer: 'Any questions?' },
    { question: 'No entiendo / no comprendo', answer: 'I don\'t understand' },
    { question: 'No recuerdo', answer: 'I don\'t remember' },
    { question: 'No sé', answer: 'I don\'t know' },
    { question: 'Puedes repetir', answer: 'Can you repeat?' },
    { question: 'Qué significa?', answer: 'What does it mean?' },
    { question: 'Qué tal?', answer: 'How are you - informal' },
    { question: 'Buenas tardes', answer: 'Good evening (after 12, but normally after 14-20 sunset)' },
    { question: 'Buenas noches', answer: 'Good night' },
    { question: 'Buenos dias', answer: 'Good morning' },
    { question: 'Hasta pronto', answer: 'See you soon' },
    { question: 'Chau', answer: 'Buy' },
    { question: 'Hasta luego', answer: 'See you later' },
    { question: 'Adios', answer: 'Buy - formal' },
    { question: 'Me llamo', answer: 'My name' },
    { question: 'Me apellido', answer: 'My surname' },
    { question: 'En que trabajas', answer: 'Whom do you work?' },
    { question: 'Donde trabajas', answer: 'Where do you work?' },
    { question: 'Los dos', answer: 'Both' },
    { question: 'Algunas', answer: 'Some' },
    { question: 'Cosa', answer: 'Thing' },
    { question: 'Hacer', answer: 'To do' },
    { question: 'Cenar', answer: 'Dinner' },
    { question: 'Escuchar', answer: 'Listen' },
    { question: 'Ver', answer: 'Watch' },
    { question: 'Salir', answer: 'Leave,<br /> Go out <br />, hangout' },
    { question: 'Visitar', answer: 'Visit' },
    { question: 'Ir de compras / hacer la compra', answer: 'Go shopping / do the grocery' },
    { question: 'Leer', answer: 'Read' },
    { question: 'Jugar + deporte/juego <br />Jugar al futbol', answer: 'PLAY Sport/game<br />Play football' },
    { question: 'Clima suave', answer: 'Mild climate' },
    { question: 'Buscar', answer: 'Search' },
    { question: 'Mejorar', answer: 'To improve' },
    { question: 'Creer', answer: 'Believe, think' },
    { question: 'Pasar', answer: 'Spend time' },
    { question: 'Elegir', answer: 'Choose' },
    { question: 'Es humedo', answer: 'It\'s wet' },
    { question: 'Viajar', answer: 'Travel' },
    { question: 'Ver', answer: 'Watch' },
    { question: 'Tocar + instrumento', answer: 'Play instrument' },
    { question: 'ACTUAR + cine, teatro, pelicula', answer: 'Play movie' },
    { question: 'Hacer senderismo', answer: 'Go hiking' },
    { question: 'Cada vez', answer: 'Each time' },
    { question: 'Una vez', answer: 'One time' },
    { question: 'Dos veces', answer: 'Two times' },
    { question: 'Tres veces', answer: '3 times' },
    { question: 'Vecino', answer: 'Neighbor' },
    { question: 'Primavera', answer: 'Spring' },
    { question: 'Pronto', answer: 'Soon' },
    { question: 'Todavia no', answer: 'Not yet' },
    { question: 'Poblada', answer: 'Populated' },
    { question: 'Peregrinaje', answer: 'Pilgrimage' },
    { question: 'Reconocimiento', answer: 'Well known' },
    { question: 'Cerca', answer: 'Next to, nearby' },
    { question: 'Casi', answer: 'Almost' },
    { question: 'Mas seguras', answer: 'More secure' },
    { question: 'Ubicacion', answer: 'Located' },
    { question: 'Llegar', answer: 'Arrive' },
    { question: 'Ademas', answer: 'Also' },
    { question: 'Alrededores', answer: 'Surroundings' },
    { question: 'Conosidas', answer: 'Well known' },
    { question: 'Valle', answer: 'Valley' },
    { question: 'Despues', answer: 'After' },
    { question: 'Norte', answer: 'North' },
    { question: 'Este', answer: 'East' },
    { question: 'Sur', answer: 'South' },
    { question: 'Oeste', answer: 'West' },
    { question: 'El sureste', answer: 'Southeast' },
    { question: 'Edificios', answer: 'Buildings' },
    { question: 'Restos', answer: 'Ruins' },
    { question: 'Poblacion', answer: 'Population' },
    { question: 'Siglos', answer: 'Centuries' },
    { question: 'El casco antiguo', answer: 'Old town' },
    { question: 'Quiza', answer: 'Maybe' },
    { question: 'Prefiero los equipos italianos', answer: 'I prefer Italian teams' },
    { question: 'Me gustaria viajar', answer: 'I would like to travel' },
    { question: 'Al menos', answer: 'At least' },
    { question: 'Gente', answer: 'People' },
    { question: 'Amable', answer: 'Kind' },
    { question: 'Arena', answer: 'Sand' },
    { question: 'Calor', answer: 'Heat' },
    { question: 'Humedo', answer: 'Humid' },
    { question: 'Llueve', answer: 'It rains' },
    { question: 'Tener ganas', answer: 'To feel like doing something' },
    { question: 'Tengo ganas de ir de vacaciones', answer: 'I really want to go on vacation' },
    { question: 'Alli', answer: 'There' },
    { question: 'Conocido', answer: 'Known, famous' },
    { question: 'Divertida', answer: 'Fun' },
    { question: 'Bebida', answer: 'Drink' },
    { question: 'Cordillera', answer: 'Mountain range' },
    { question: 'Hace sol', answer: 'It\'s sunny' },
    { question: 'Hace calor', answer: 'It\'s hot' },
    { question: 'Hace frio', answer: 'It\'s cold' },
    { question: 'Hace viento', answer: 'It\'s windy' },
    { question: 'Esta nublado', answer: 'It\'s cloudy' },
    { question: 'Es seco', answer: 'It\'s dry' },
    { question: 'La primavera', answer: 'Spring' },
    { question: 'El verano', answer: 'Summer' },
    { question: 'El otoño', answer: 'Autumn' },
    { question: 'El invierno', answer: 'Winter' },
    
  ];
  export default flashcards;